### ISSUE TITLE
[cinder-csi-plugin] Permission denied when Selinux is enabled

### ISSUE THREAD

**Issue by brtknr** [kubernetes/cloud-provider-openstack#973] opened 2020-03-13 11:55 UTC
**BUG REPORT**:

/kind bug

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
I get a permission denied when I try to read/write to a Persistent Volume with Cinder backend

**What you expected to happen**:
I expect to be able to read and write to it.

**How to reproduce it**:
Deploy a Kubernetes cluster using OpenStack Magnum, the new Fedora CoreOS driver, with "volume_driver=cinder" option, deploy a pod with a Cinder volume attached and try and write to it. 

**Anything else we need to know?**:
It works when selinux is disabled on the worker node.

This is what I see in the SElinux audit log:
```
Mar 12 14:10:31 k8s-flannel-coreos-4abm32zh5nin-node-0 audit[16142]: AVC avc:  denied  { read } for  pid=16142 comm="ls" name="/" dev="vdb" ino=2 scontext=system_u:system_r:container_t:s0:c501,c741 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=1
Mar 12 14:10:53 k8s-flannel-coreos-4abm32zh5nin-node-0 audit[16216]: AVC avc:  denied  { write } for  pid=16216 comm="touch" name="/" dev="vdb" ino=2 scontext=system_u:system_r:container_t:s0:c501,c741 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=1
Mar 12 14:10:53 k8s-flannel-coreos-4abm32zh5nin-node-0 audit[16216]: AVC avc:  denied  { add_name } for  pid=16216 comm="touch" name="hello2" scontext=system_u:system_r:container_t:s0:c501,c741 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=1
Mar 12 14:10:53 k8s-flannel-coreos-4abm32zh5nin-node-0 audit[16216]: AVC avc:  denied  { create } for  pid=16216 comm="touch" name="hello2" scontext=system_u:system_r:container_t:s0:c501,c741 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
Mar 12 14:10:53 k8s-flannel-coreos-4abm32zh5nin-node-0 audit[16216]: AVC avc:  denied  { write open } for  pid=16216 comm="touch" path="/usr/share/nginx/html/hello2" dev="vdb" ino=13 scontext=system_u:system_r:container_t:s0:c501,c741 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
```

This is what I see in the cinder-csi-plugin log:
```
I0312 15:59:23.084423       1 driver.go:57] Driver: cinder.csi.openstack.org version: 1.1.0
I0312 15:59:23.085012       1 driver.go:90] Enabling controller service capability: LIST_VOLUMES
I0312 15:59:23.085049       1 driver.go:90] Enabling controller service capability: CREATE_DELETE_VOLUME
I0312 15:59:23.085064       1 driver.go:90] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0312 15:59:23.085076       1 driver.go:90] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0312 15:59:23.085087       1 driver.go:90] Enabling controller service capability: LIST_SNAPSHOTS
I0312 15:59:23.085099       1 driver.go:90] Enabling controller service capability: EXPAND_VOLUME
I0312 15:59:23.085118       1 driver.go:102] Enabling volume access mode: SINGLE_NODE_WRITER
I0312 15:59:23.085131       1 driver.go:112] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0312 15:59:23.085155       1 driver.go:112] Enabling node service capability: EXPAND_VOLUME
I0312 15:59:23.086897       1 openstack.go:80] Block storage opts: {0}
I0312 15:59:23.201087       1 server.go:108] Listening for connections on address: &net.UnixAddr{Name:"/csi/csi.sock", Net:"unix"}
I0312 16:02:59.426352       1 mount_linux.go:287] `fsck` error fsck from util-linux 2.29.2
fsck.ext2: Bad magic number in super-block while trying to open /dev/vdb
/dev/vdb: 
The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

E0312 16:02:59.441254       1 mount_linux.go:140] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/disk/by-id/virtio-36cfa8f2-169a-49a1-9 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4fc494af-97eb-4458-b1e5-366662e6ec30/globalmount
Output: mount: wrong fs type, bad option, bad superblock on /dev/vdb,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

I0312 16:02:59.461028       1 mount_linux.go:322] Disk "/dev/disk/by-id/virtio-36cfa8f2-169a-49a1-9" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/disk/by-id/virtio-36cfa8f2-169a-49a1-9]
I0312 16:02:59.831015       1 mount_linux.go:326] Disk successfully formatted (mkfs): ext4 - /dev/disk/by-id/virtio-36cfa8f2-169a-49a1-9 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4fc494af-97eb-4458-b1e5-366662e6ec30/globalmount
```

**Environment**:
- openstack-cloud-controller-manager version: 1.17.0
- OpenStack version: Train (using magnum)
- Others: Fedora CoreOS 31
- Kubernetes versions tried: 1.17.3, 1.17.4

**Comment by brtknr** [comment] 2020-03-14 19:52
Relevant story on storyboard: https://storyboard.openstack.org/#!/story/2007413

**Comment by chrigl** [comment] 2020-03-22 13:29
Hey @brtknr . I am not able to reproduce this with cinder-csi-plugin v1.17.0 and latest, against kubernetes v1.17.4.


I set up a 2 node cluster using kubeadm and kubelet of the official RH repos form the kubeadm documentation and `rpm-ostree install kubeadm kubelet kubectl`. I created a pod on one node, created a file, deleted the pod and verified working on the other node.

```
[root@host-10-0-0-32 ~]# kubectl get pods -owide                                                                                                                                                 
NAME    READY   STATUS    RESTARTS   AGE   IP           NODE             NOMINATED NODE   READINESS GATES                                                                                        web-0   1/1     Running   0          39s   10.244.1.2   host-10-0-0-16   <none>           <none>

[root@host-10-0-0-32 ~]# kubectl exec -ti web-0 /bin/bash
root@web-0:/# echo foo > /usr/share/nginx/html/hello                                                                                                                                             root@web-0:/# exit  

[root@host-10-0-0-32 ~]# kubectl cordon host-10-0-0-16                                                                                                                                           node/host-10-0-0-16 cordoned                                                                                                                                                                     
[root@host-10-0-0-32 ~]# kubectl delete pod web-0                                                                                                                                                pod "web-0" deleted 

[root@host-10-0-0-32 ~]# kubectl get pods -owide
NAME    READY   STATUS    RESTARTS   AGE   IP           NODE             NOMINATED NODE   READINESS GATES
web-0   1/1     Running   0          24s   10.244.0.7   host-10-0-0-32   <none>           <none>

[root@host-10-0-0-32 ~]# kubectl exec -ti web-0 /bin/bash
root@web-0:/# echo "baz" >> /usr/share/nginx/html/hello 
root@web-0:/# cat /usr/share/nginx/html/hello 
foo                                             
baz  
```

Also, the mounts are done by context rather.

on host-10-0-0-16
```
[root@host-10-0-0-16 ~]# ls -lZd /var/lib/kubelet/pods/6764fe5f-467d-4a55-a338-699d6e833ead/volumes/kubernetes.io~csi/pvc-30eb062e-7a9d-4120-87ae-19191c1629a5/mount/
drwxr-xr-x. 3 root root system_u:object_r:container_file_t:s0:c41,c117 4096 Mar 22 13:05 /var/lib/kubelet/pods/6764fe5f-467d-4a55-a338-699d6e833ead/volumes/kubernetes.io~csi/pvc-30eb062e-7a9d-4120-87ae-19191c1629a5/mount/
```

after deleting the pod on host-10-0-0-32
```
[root@host-10-0-0-32 ~]# ls -lZd /var/lib/kubelet/pods/096dda7c-a065-46a5-97c1-1a396bc47e17/volumes/kubernetes.io~csi/pvc-30eb062e-7a9d-4120-87ae-19191c1629a5/mount/
drwxr-xr-x. 3 root root system_u:object_r:container_file_t:s0:c917,c1004 4096 Mar 22 13:05 /var/lib/kubelet/pods/096dda7c-a065-46a5-97c1-1a396bc47e17/volumes/kubernetes.io~csi/pvc-30eb062e-7a9d-4120-87ae-19191c1629a5/mount/
```

```
[root@host-10-0-0-32 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

[root@host-10-0-0-32 ~]# getenforce 
Enforcing
[root@host-10-0-0-16 ~]# getenforce 
Enforcing

[root@host-10-0-0-32 ~]# rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
* ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 31.20200310.2.0 (2020-03-12T01:21:36Z)
                BaseCommit: fef0f5a226ebf0e9915d8ee03a3bc70d3cc0593f0c22841264b3bc906dff0957
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: kubeadm kubectl kubelet

  ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 31.20200310.2.0 (2020-03-12T01:21:36Z)
                    Commit: fef0f5a226ebf0e9915d8ee03a3bc70d3cc0593f0c22841264b3bc906dff0957
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4


[root@host-10-0-0-16 ~]# rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
* ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 31.20200310.2.0 (2020-03-12T01:21:36Z)
                BaseCommit: fef0f5a226ebf0e9915d8ee03a3bc70d3cc0593f0c22841264b3bc906dff0957
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: kubeadm kubectl kubelet

  ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 31.20200310.2.0 (2020-03-12T01:21:36Z)
                    Commit: fef0f5a226ebf0e9915d8ee03a3bc70d3cc0593f0c22841264b3bc906dff0957
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4

```

Closing it for now, but please feel free to re-open with simple steps to recreate.

/close

**Closed** 2020-03-22 13:29 UTC
Labels: kind/bug

**Comment by brtknr** [comment] 2020-03-22 16:27
Openstack magnum currently uses hyperkube images, I wonder if the issue lies there? Thanks for trying to reproduce it, I will investigate further from my end

**Comment by lingxiankong** [comment] 2020-03-22 20:19
@brtknr One suggestion, when you find it's still not working in Magnum cluster, then just bootstrap a cluster without using Magnum (e.g. using kubeadm as @chrigl mentioned) on the host OS you prefer to avoid distractions.

**Comment by brtknr** [comment] 2020-03-23 12:22
I managed to fix the issue by mounting /:/rootfs:ro into the Kubelet hyperkube container. Thanks everybody for your help.
