### ISSUE TITLE
Question: Deploy the csi plugin for cinder in Kubernetes

### ISSUE THREAD

**Issue by darcyllingyan** [kubernetes/cloud-provider-openstack#486] opened 2019-02-18 05:29 UTC
Hi,
I'm new to the Cinder CSI, now I just want to integrate the Cinder CSI to my kubernetes cluster.
I have several questions:

1) If I just want to deploy the cinder CSI, whether it's OK for me to download the pkg/csi/cinder only?
https://github.com/kubernetes/cloud-provider-openstack/tree/master/pkg/csi/cinder
2) If no, whether there is better way fro me to only deploy it?
3) If yes, The pkg/csi/cinder only implements the CSI driver and I need to deploy the CSI sidercars seperately, right?
3) If yes, how to install the Cinder CSI, as the package doesn't have appropriate docs.

Thanks

**Comment by adisky** [comment] 2019-02-18 05:36
@darcyllingyan you can reach us via email or slack for queries, github 
https://github.com/kubernetes/community/tree/master/sig-openstack#contact
Please check the docs also 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md

**Comment by lingxiankong** [comment] 2019-02-18 18:56
Hi @darcyllingyan 

1. The best way to deploy cinder csi plugin is to use manifest files in manifests/cinder-csi-plugin folder. You don't directly choose which folder to use.
2. For how to deploy the manifests, see the doc @adisky mentioned, you could see all the secrets there.
3. You can find more detailed information about deploying CSI [here](https://kubernetes-csi.github.io/docs/)

Please let me know if you have any further questions.

**Comment by darcyllingyan** [comment] 2019-02-19 08:59
Hi @lingxiankong ,
 Thanks very much for the response.
Based on the doc @adisky mentioned, I followed the **Deploy** part, when deploy the csi plugin, the error "Error: container has runAsNonRoot and image will run as root" is always reported.
note: I use ```docker pull quay.io/k8scsi/csi-attacher:v0.4.1``` to get the image to local, and push the image to my private registry.
Do you have any comments? Thanks!

```
# ls ../cloud-provider-openstack/
bindep.txt  cmd                 contrib          devstack  examples    Gopkg.toml  LICENSE   manifests  pkg        SECURITY_CONTACTS  staging
cluster     code-of-conduct.md  CONTRIBUTING.md  docs      Gopkg.lock  hack        Makefile  OWNERS     README.md  snapcraft.yaml     tools

#kubectl apply -f manifests/cinder-csi-plugin
service/csi-attacher-cinderplugin unchanged
statefulset.apps/csi-attacher-cinderplugin configured
serviceaccount/csi-attacher unchanged
clusterrole.rbac.authorization.k8s.io/external-attacher-runner unchanged
clusterrolebinding.rbac.authorization.k8s.io/csi-attacher-role unchanged
daemonset.apps/csi-nodeplugin-cinderplugin unchanged
serviceaccount/csi-nodeplugin unchanged
clusterrole.rbac.authorization.k8s.io/csi-nodeplugin unchanged
clusterrolebinding.rbac.authorization.k8s.io/csi-nodeplugin unchanged
service/csi-provisioner-cinderplugin unchanged
statefulset.apps/csi-provisioner-cinderplugin configured
serviceaccount/csi-provisioner unchanged
clusterrole.rbac.authorization.k8s.io/external-provisioner-runner unchanged
clusterrolebinding.rbac.authorization.k8s.io/csi-provisioner-role unchanged
secret/csi-secret-cinderplugin configured

# kubectl get pod
NAME                             READY   STATUS                       RESTARTS   AGE
csi-attacher-cinderplugin-0      0/2     CreateContainerConfigError   0          3s

# kubectl describe pod csi-attacher-cinderplugin-0
Events:
  Type     Reason     Age              From                          Message
  ----     ------     ----             ----                          -------
  Normal   Scheduled  8s               default-scheduler             Successfully assigned default/csi-attacher-cinderplugin-0 to bcmt-rook-worker-01
  Normal   Pulled     7s (x2 over 7s)  kubelet, bcmt-rook-worker-01  Container image "bcmt-registry:5000/quay.io/k8scsi/csi-attacher:v0.4.1" already present on machine
  Warning  Failed     7s (x2 over 7s)  kubelet, bcmt-rook-worker-01  Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     7s (x2 over 7s)  kubelet, bcmt-rook-worker-01  Container image "bcmt-registry:5000/docker.io/k8scloudprovider/cinder-csi-plugin:latest" already present on machine
  Warning  Failed     7s (x2 over 7s)  kubelet, bcmt-rook-worker-01  Error: container has runAsNonRoot and image will run as root
```

**Comment by lingxiankong** [comment] 2019-02-19 11:33
Hi, seems like you have a PodSecurityPolicy resource defined which prevents pods from running with root privileges.

**Comment by jichenjc** [comment] 2019-02-20 05:29
yeah, seems the security policy is the root cause, and FYI, the master image already changed to quay.io/k8scsi/csi-attacher:v1.0.1

**Comment by darcyllingyan** [comment] 2019-02-20 07:20
Hi @lingxiankong , @jichenjc ,
Thanks for the response!
Yes, it's the security policy issue. After change the security now the plugin has been started.
But Now the attacher plugin has one creash issue. Below is the logs, do you have any suggestions? Thanks!
```
# kubectl get pod -n kube-system
NAME                                           READY   STATUS             RESTARTS   AGE
csi-attacher-cinderplugin-0                    1/2     CrashLoopBackOff   24         126m
csi-nodeplugin-cinderplugin-2zq9d              2/2     Running            0          128m
csi-provisioner-cinderplugin-0                 2/2     Running            0          125m

# kubectl logs -f csi-attacher-cinderplugin-0 -n kube-system csi-attacher
I0220 07:09:33.099943       1 main.go:77] Version: v0.4.2-0-g1e6a4a1
I0220 07:09:33.101961       1 connection.go:89] Connecting to /var/lib/csi/sockets/pluginproxy/csi.sock
I0220 07:09:33.102352       1 connection.go:116] Still trying, connection is CONNECTING
I0220 07:09:33.102986       1 connection.go:113] Connected
I0220 07:09:33.103001       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:33.103006       1 connection.go:237] GRPC request: {}
I0220 07:09:33.106062       1 connection.go:239] GRPC response: {}
I0220 07:09:33.106602       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:33.106616       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:34.106770       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:34.106821       1 connection.go:237] GRPC request: {}
I0220 07:09:34.109506       1 connection.go:239] GRPC response: {}
I0220 07:09:34.109853       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:34.109865       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:35.110016       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:35.110063       1 connection.go:237] GRPC request: {}
I0220 07:09:35.111114       1 connection.go:239] GRPC response: {}
I0220 07:09:35.111844       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:35.111862       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:36.112156       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:36.112212       1 connection.go:237] GRPC request: {}
I0220 07:09:36.113184       1 connection.go:239] GRPC response: {}
I0220 07:09:36.113596       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:36.113608       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:37.113797       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:37.113846       1 connection.go:237] GRPC request: {}
I0220 07:09:37.114809       1 connection.go:239] GRPC response: {}
I0220 07:09:37.115272       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:37.115285       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:38.115561       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:38.115589       1 connection.go:237] GRPC request: {}
I0220 07:09:38.116547       1 connection.go:239] GRPC response: {}
I0220 07:09:38.117100       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:38.117112       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:39.117289       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:39.117350       1 connection.go:237] GRPC request: {}
I0220 07:09:39.118476       1 connection.go:239] GRPC response: {}
I0220 07:09:39.119003       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:39.119029       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:40.119230       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:40.119302       1 connection.go:237] GRPC request: {}
I0220 07:09:40.121217       1 connection.go:239] GRPC response: {}
I0220 07:09:40.124025       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:40.124052       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:41.124359       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:41.124387       1 connection.go:237] GRPC request: {}
I0220 07:09:41.125506       1 connection.go:239] GRPC response: {}
I0220 07:09:41.125839       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:41.125854       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:42.126035       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:42.126085       1 connection.go:237] GRPC request: {}
I0220 07:09:42.127115       1 connection.go:239] GRPC response: {}
I0220 07:09:42.127502       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:42.127520       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:43.127682       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:43.127726       1 connection.go:237] GRPC request: {}
I0220 07:09:43.128624       1 connection.go:239] GRPC response: {}
I0220 07:09:43.128964       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:43.128977       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:44.129184       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:44.129217       1 connection.go:237] GRPC request: {}
I0220 07:09:44.130103       1 connection.go:239] GRPC response: {}
I0220 07:09:44.130612       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:44.130624       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:45.130818       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:45.130872       1 connection.go:237] GRPC request: {}
I0220 07:09:45.132024       1 connection.go:239] GRPC response: {}
I0220 07:09:45.132505       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:45.132525       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:46.132744       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:46.132836       1 connection.go:237] GRPC request: {}
I0220 07:09:46.133919       1 connection.go:239] GRPC response: {}
I0220 07:09:46.134425       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:46.134459       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:47.134681       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:47.134734       1 connection.go:237] GRPC request: {}
I0220 07:09:47.137227       1 connection.go:239] GRPC response: {}
I0220 07:09:47.137684       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:47.137698       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:48.137924       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:48.137979       1 connection.go:237] GRPC request: {}
I0220 07:09:48.139113       1 connection.go:239] GRPC response: {}
I0220 07:09:48.139536       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:48.139552       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:49.139767       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:49.139825       1 connection.go:237] GRPC request: {}
I0220 07:09:49.140710       1 connection.go:239] GRPC response: {}
I0220 07:09:49.141161       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:49.141196       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:50.141420       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:50.141506       1 connection.go:237] GRPC request: {}
I0220 07:09:50.142408       1 connection.go:239] GRPC response: {}
I0220 07:09:50.142788       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:50.142802       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:51.143096       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:51.143166       1 connection.go:237] GRPC request: {}
I0220 07:09:51.144563       1 connection.go:239] GRPC response: {}
I0220 07:09:51.144992       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:51.145016       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:52.145211       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:52.145302       1 connection.go:237] GRPC request: {}
I0220 07:09:52.146367       1 connection.go:239] GRPC response: {}
I0220 07:09:52.146867       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:52.146882       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:53.147060       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:53.147091       1 connection.go:237] GRPC request: {}
I0220 07:09:53.148191       1 connection.go:239] GRPC response: {}
I0220 07:09:53.149155       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:53.149170       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:54.150607       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:54.150658       1 connection.go:237] GRPC request: {}
I0220 07:09:54.151799       1 connection.go:239] GRPC response: {}
I0220 07:09:54.152233       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:54.152246       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:55.152523       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:55.152566       1 connection.go:237] GRPC request: {}
I0220 07:09:55.153742       1 connection.go:239] GRPC response: {}
I0220 07:09:55.154387       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:55.154411       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:56.154593       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:56.154643       1 connection.go:237] GRPC request: {}
I0220 07:09:56.155702       1 connection.go:239] GRPC response: {}
I0220 07:09:56.156223       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:56.156240       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:57.156567       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:57.156646       1 connection.go:237] GRPC request: {}
I0220 07:09:57.157734       1 connection.go:239] GRPC response: {}
I0220 07:09:57.158160       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:57.158187       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:58.158388       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:58.158513       1 connection.go:237] GRPC request: {}
I0220 07:09:58.159551       1 connection.go:239] GRPC response: {}
I0220 07:09:58.159915       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:58.159930       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:59.160196       1 connection.go:236] GRPC call: /csi.v0.Identity/Probe
I0220 07:09:59.160262       1 connection.go:237] GRPC request: {}
I0220 07:09:59.161200       1 connection.go:239] GRPC response: {}
I0220 07:09:59.161623       1 connection.go:240] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
I0220 07:09:59.161639       1 main.go:218] Probe failed with rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
```

**Comment by ramineni** [comment] 2019-02-20 07:48
@darcyllingyan looks like you are using older image , could you check if your are using latest images only as @jichenjc pointed. quay.io/k8scsi/csi-attacher:v1.0.1?

**Comment by adisky** [comment] 2019-02-20 08:34
@darcyllingyan Please use compatible versions of csi cinder plugin and sidecar containars
if  attacher/provisoner/registrar are at 0.4.x then use k8scloudprovider/cinder-csi-plugin:1.13.1 (csi 0.3.0)
if attacher/provisoner/registrar are at 1.0.x then use k8scloudprovider/cinder-csi-plugin:latest (csi 1.0.0)
There are breaking changes between csi0.3.0 and csi 1.0.0

**Comment by darcyllingyan** [comment] 2019-02-20 08:37
Hi @ramineni ,
Thanks for the information.
Yes, the attacher image is old, and after use the v1.0.1. The ERROR has been solved.

But there is another issue:
When I create the PVC, the PVC is Pending status, and after check the log, it shows as below:

Based on the log, it reports the "x509: certificate signed by unknown authority", as now the openstack certificate we used is signed non-official, whether there is an interface for me to pass my own certificates?

```
# cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-cinderplugin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-sc-cinderplugin
# kubectl apply -f pvc.yaml 
persistentvolumeclaim/csi-pvc-cinderplugin created

# kubectl get pvc
NAME                   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS          AGE
csi-pvc-cinderplugin   Pending                                      csi-sc-cinderplugin   7s
# kubectl describe pvc csi-pvc-cinderplugin
Events:
  Type       Reason                Age               From                                                                                  Message
  ----       ------                ----              ----                                                                                  -------
  Normal     ExternalProvisioning  4s (x4 over 17s)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "csi-cinderplugin" or manually created by system administrator
  Normal     Provisioning          1s (x3 over 17s)  csi-cinderplugin_csi-provisioner-cinderplugin-0_4bb1a2a3-34cc-11e9-8cc5-b27933f5fb30  External provisioner is provisioning volume for claim "default/csi-pvc-cinderplugin"
  Warning    ProvisioningFailed    1s (x3 over 16s)  csi-cinderplugin_csi-provisioner-cinderplugin-0_4bb1a2a3-34cc-11e9-8cc5-b27933f5fb30  failed to provision volume with StorageClass "csi-sc-cinderplugin": rpc error: code = Unknown desc = Post https://10.75.225.36:13000/v3/auth/tokens: x509: certificate signed by unknown authority
Mounted By:  nginx
```


si-cinderplugin_csi-provisioner-cinderplugin-0_4bb1a2a3-34cc-11e9-8cc5-b27933f5fb30  failed to provision volume with StorageClass "csi-sc-cinderplugin": rpc error: code = Unknown desc = Post https://10.75.225.36:13000/v3/auth/tokens: x509: certificate signed by unknown authority
```

Thanks

**Comment by darcyllingyan** [comment] 2019-02-20 08:56
Hi @adisky,
Thanks for the information. It's useful information and now I have use the compatible versions between csi cinder plugin and sidecar containars.

Thanks

**Comment by jianglingxia** [comment] 2019-02-21 03:08
@darcyllingyan 
my problem same with you that the pv can not dynamic created,
Events:
  Type     Reason                Age                From                                                                                  Message
  ----     ------                ----               ----                                                                                  -------
  Normal   Provisioning          6m (x11 over 1h)   csi-cinderplugin_csi-provisioner-cinderplugin-0_acde092b-3576-11e9-8591-0a58ac10000a  External provisioner is provisioning volume for claim "default/csi-pvc-cinderplugin"
  Warning  ProvisioningFailed    6m (x11 over 1h)   csi-cinderplugin_csi-provisioner-cinderplugin-0_acde092b-3576-11e9-8591-0a58ac10000a  failed to provision volume with StorageClass "csi-sc-cinderplugin": rpc error: code = Unknown desc = No suitable endpoint could be found in the service catalog.
  Normal   ExternalProvisioning  3m (x343 over 1h)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "csi-cinderplugin" or manually created by system administrator

the three pod can running:
[root@host-101-101-101-134 csi]# kubectl get po --all-namespaces -w                                                       
NAMESPACE     NAME                                READY     STATUS    RESTARTS   AGE
kube-system   csi-attacher-cinderplugin-0         2/2       Running   0          17h
kube-system   csi-nodeplugin-cinderplugin-6l6mw   2/2       Running   1          17h
kube-system   csi-provisioner-cinderplugin-0      2/2       Running   0          1h
kube-system   kube-flannel-wd54d                  2/2       Running   1          1d


and exec the command can connect the openstack 
[root@host-101-101-101-134 csi]# curl -X GET  'http://169.254.169.254/openstack/2012-08-10/meta_data.json'
{"availability_zone": "nova", "hostname": "storage.novalocal", "launch_index": 0, "uuid": "a2006d12-99dc-46ef-89bc-5ce3266413b6", "name": "storage"}

[root@host-101-101-101-134 logs]# kubectl exec -it csi-provisioner-cinderplugin-0 -n kube-system -c cinder /bin/bash         
[root@csi-provisioner-cinderplugin-0 /]# env
CSI_ATTACHER_CINDERPLUGIN_PORT=tcp://10.254.73.13:12345
HOSTNAME=csi-provisioner-cinderplugin-0
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://10.254.0.1:443
CSI_PROVISIONER_CINDERPLUGIN_PORT_12345_TCP_ADDR=10.254.248.149
CSI_PROVISIONER_CINDERPLUGIN_PORT=tcp://10.254.248.149:12345
KUBERNETES_SERVICE_PORT=443
CLUSTER_NAME=kubernetes
CLOUD_CONFIG=/etc/config/cloud.conf
KUBERNETES_SERVICE_HOST=10.254.0.1
CSI_PROVISIONER_CINDERPLUGIN_PORT_12345_TCP=tcp://10.254.248.149:12345
CSI_ENDPOINT=unix://csi/csi.sock
can help me with it?thanks

**Comment by adisky** [comment] 2019-02-22 07:34
@darcyllingyan as you have opened another issue for tracking, certificate error, closing this one
/close

**Closed by adisky** 2019-02-22 07:34 UTC
