### ISSUE TITLE
[manila-csi-plugin] unable to add the helm repo

### ISSUE THREAD

**Issue by JPRbrs** [kubernetes/cloud-provider-openstack#1202] opened 2020-09-14 06:02 UTC
/kind bug

What happened: I'm unable to add the helm repo for manila-csi-plugin following instructions in github pages readme

Error: Looks like "https://kubernetes.github.io/cloud-provider-openstack" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes.github.io/cloud-provider-openstack/index.yaml : 404 Not Found

It seemed that https://github.com/kubernetes/cloud-provider-openstack/issues/1193 should have solved the problem but I'm still getting the error. As per the commit in 1193, I understand the functionality to use the github repo as helm repo is not going to be provided but I can still see the reference to 
`
helm repo add cpo https://kubernetes.github.io/cloud-provider-openstack
helm repo update
`

Can you please clarify if that is supposed to be working?

What you expected to happen: Helm repo is installed when issuing the following command:

helm repo add cpo https://kubernetes.github.io/cloud-provider-openstack

How to reproduce it:
issue the command below:
https://github.com/kubernetes/cloud-provider-openstack/blob/gh-pages/README.md

Anything else we need to know?:
As stated in the official documentation A valid chart repository must have an index file but I've noticed that the index.yaml file was recently removed in PR 1191, can that be the cause?

Environment:

Helm: Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**Comment by ramineni** [comment] 2020-09-18 09:35
@brtknr Could you have look at this?

**Comment by brtknr** [comment] 2020-09-18 09:36
@ramineni requires https://github.com/kubernetes/cloud-provider-openstack/pull/1216

**Comment by brtknr** [comment] 2020-09-28 10:28
The issue has been addressed, index.yaml was generated this morning: https://github.com/kubernetes/cloud-provider-openstack/blob/gh-pages/index.yaml so this should work now. Please close the issue.

**Comment by JPRbrs** [comment] 2020-09-28 10:42
I can confirm it works now, thanks!!

**Comment by isantospardo** [comment] 2020-09-28 10:51
Hi, when trying to use helm, I see the same issue, is there any known workaround for this?
`helm pull  --repo https://github.com/kubernetes/cloud-provider-openstack.git charts/`
Error:
`Error: looks like "https://github.com/kubernetes/cloud-provider-openstack.git" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/kubernetes/cloud-provider-openstack.git/index.yaml : 404 Not Found`

**Comment by brtknr** [comment] 2020-09-28 10:53
That is not how you use it. Please see instructions on https://kubernetes.github.io/cloud-provider-openstack

**Comment by isantospardo** [comment] 2020-09-28 10:54
Yes, but I would like to pull this helm chart using argo-cd, if it would be possible, that is why I am doing this, just in case there is a workaround.

**Comment by brtknr** [comment] 2020-09-28 10:55
Then try `helm pull https://kubernetes.github.io/cloud-provider-openstack`

**Comment by ramineni** [comment] 2020-09-30 05:42
/close 
Helm repo is working now as confirmed above.
@isantospardo you can raise new issue , if you are still having issues.

**Closed** 2020-09-30 05:42 UTC
Labels: kind/bug
