### ISSUE TITLE
failed to start container "cinder-csi-plugin"

### ISSUE THREAD

**Issue by celiawa** [kubernetes/cloud-provider-openstack#833] opened 2019-11-14 02:40 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Very frequently the cinder-csi-plugin container in the daemenset of csi-cinder-nodeplugin failed to start with following error.   Sometimes the container can start normally.
  Normal   Created    9m5s (x5 over 10m)    kubelet, celia-control-02  Created container cinder-csi-plugin
  Warning  Failed     8m50s (x5 over 10m)   kubelet, celia-control-02  Error: failed to start container "cinder-csi-plugin": Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely"
  Warning  BackOff    40s (x33 over 9m31s)  kubelet, celia-control-02  Back-off restarting failed container
 
If I remove the mountpoint /var/lib/kubelet from cinder-csi-nodeplugin.yaml. Every time the pods can start successfully.  MountFlags=shared is set in docker.service.  
- name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"

**What you expected to happen**:
Every time the cinder-csi-plugin container can start successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: v1.16.0
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ramineni** [comment] 2019-11-14 02:59
@celiawa Are you facing this issue with master branch as well?

**Comment by celiawa** [comment] 2019-11-14 03:15
yes, the master branch as well.  I just tried with the other images, also has this issue as long as I mount with /var/lib/kubelet, the container failed to start with this error. So seems not the cinder csi issue. 
And could you pls help to confirm whether can we mount with /var/lib/kubelet/pods instead /var/lib/kubelet, as I can start the csi container with mountpoint /var/lib/kubelet/pods.

**Comment by ramineni** [comment] 2019-11-14 04:51
@celiawa /var/lib/kubelet is required to support block volume , its introduced in https://github.com/kubernetes/cloud-provider-openstack/pull/563 , so /var/lib/kubelet/pods is removed in https://github.com/kubernetes/cloud-provider-openstack/pull/773 .

Are you using the exact same manifest https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml ? with previleged:true etc? Could you share the container logs with verbose enabled?

**Comment by celiawa** [comment] 2019-11-29 05:57
Thanks. The issue is not reproducible now after we enlarge the flavor of our node.  The ticket can be closed.

**Comment by ramineni** [comment] 2019-11-29 06:00
Ok, Thanks. Closing the same. Please reopen if the issue is seen again
/close

**Closed by ramineni** 2019-11-29 06:00 UTC
