### ISSUE TITLE
Release v1.26.0 have docker tag "latest" in manifest files

### ISSUE THREAD

**Issue by huxcrux** [kubernetes/cloud-provider-openstack#2085] opened 2023-02-01 15:46 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug
> /kind feature

**What happened**:
The latest release v1.26.0 have docker tag "latest" in manifest files. I first noticed this in the "manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml" file however this issue seems to also affect other manifests.

**What you expected to happen**:
I expected the release manifests to have tagged versions of all docker containers

**How to reproduce it**:
N/A

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.26.0
- OpenStack version:
- Others:

**Comment by zetaab** [comment] 2023-02-01 17:07
https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.26/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml#L41 I do not see what is the issue here?

**Comment by bl0m1** [comment] 2023-02-02 09:41
It looks like the [Github Release](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.26.0) points towards the v1.26.0 tag in this tag has "latest": https://github.com/kubernetes/cloud-provider-openstack/blob/v1.26.0/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml#L41

It looks like the release-1.26 branch is correct, maybe the release/tag was created from the wrong branch?

**Comment by Jonher937** [comment] 2023-02-13 17:21
Had the same issue today where I installed cinder-csi from v1.26.0 tag and got an older `cinder-csi-plugin` version than I was running previously. Indeed the release branch looks OK as @bl0m1 mentioned and @zetaab confirmed.

The commit the GitHub release v1.26.0 was created from is before the two latest commits from @zetaab on the release branch.
* Branch: https://github.com/kubernetes/cloud-provider-openstack/commits/release-1.26
* Tag: https://github.com/kubernetes/cloud-provider-openstack/commits/v1.26.0

**Comment by zetaab** [comment] 2023-02-20 16:38
please check the latest versions is this solved?

**Comment by bl0m1** [comment] 2023-02-22 08:43
> please check the latest versions is this solved?

I can confirm this is fixed in tag "v1.26.1" :)

**Comment by Jonher937** [comment] 2023-02-22 09:18
v1.26.1 looks good.

Why I noticed the same problem as bl0m1 is because the `:latest` tag seems multiple months old. I tried looking in `docker.io/k8scloudprovider/cinder-csi-plugin:latest` starting `/bin/cinder-csi-plugin --version` but there was no version flag.
However `stat` shows this:
```
# stat /bin/cinder-csi-plugin
  File: /bin/cinder-csi-plugin
  Size: 31727616  	Blocks: 61968      IO Block: 4096   regular file
Device: 42h/66d	Inode: 6432784     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-05-20 11:27:10.000000000 +0000
Modify: 2022-05-20 11:27:10.000000000 +0000
```
So if `:latest` is used in development branches it needs to be updated. I don't know if this is true for and of the other images.

**Comment by zetaab** [comment] 2023-02-22 10:33
our ci pipelines are not updating latest tag currently at all

**Closed** 2024-01-18 23:59 UTC
Labels: lifecycle/rotten, kind/bug

**Comment by dulek** [comment] 2024-01-19 14:16
```
mdulko:~/ $ podman pull registry.k8s.io/kubernetes/kube-apiserver:latest 
Trying to pull registry.k8s.io/kubernetes/kube-apiserver:latest...
Error: initializing source docker://registry.k8s.io/kubernetes/kube-apiserver:latest: reading manifest latest in registry.k8s.io/kubernetes/kube-apiserver: manifest unknown: Failed to fetch "latest"
```

I think this is a convention here, KAS doesn't have `:latest` as well.
