### ISSUE TITLE
[csi-cinder-provisioner] cloud.conf can add more feild that support keystone re-authentication?

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/cloud-provider-openstack#1119] opened 2020-07-15 12:57 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

provisioner logs 
Failed to GetOpenStackProvider: failed to read and parse /etc/ca.pem certificate: open /etc/ca.pem: no such file or directory

why the log can not find the pem file?

but the cloud.conf is 

/etc/config # cat cloud.conf 
[Global]
username=test
password=111
auth-url=https://10.10.0.1:5000/v2.0/
tenant-id=11111111111111111111111111
ca-file=/etc/ca.pem

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:k8s v1.17
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jianglingxia** [comment] 2020-07-15 13:01
@ramineni can help me?

**Comment by ramineni** [comment] 2020-07-15 13:15
@jianglingxia which manifests file have you used to deploy? and have you created secret with this file?

**Comment by jianglingxia** [comment] 2020-07-15 14:31
https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml

Used the yaml before deployed I will created the secret with the cloud.conf based64 value

but logs print can not find the cafile

**Comment by jianglingxia** [comment] 2020-07-16 00:13
[Global]
region=RegionOne
username=username
password=password
auth-url=https://openstack.cloud:5000/v3
tenant-id=14ba698c0aec4fd6b7dc8c310f664009
domain-id=default
ca-file=/etc/ca.pem

I0715 11:30:41.259525       1 main.go:119] <<<< main.go GetOpenStackProvider function begin>>>>>
W0715 11:30:41.259539       1 main.go:122] Failed to GetOpenStackProvider: failed to read and parse /etc/ca.pem certificate: open /etc/ca.pem: no such file or directory

why the controller plugin container can not find the file? thanks

**Comment by jianglingxia** [comment] 2020-07-16 02:08
the problem maybe the cinder-plugin yaml has not the volume cacert

NOTE: if your openstack cloud has cert (which means you already has ca-file definition in cloud-config), please make sure that you also updated the volumes list of cinder-csi-controllerplugin.yaml and cinder-csi-nodeplugin.yaml to include the cacert. e.g following sample then mount the volume to the pod as well.


but now the plugin logs error: post /v2.0/tokens error message 
400 no required ssl certificate was sent ........

where is error?

**Comment by jianglingxia** [comment] 2020-07-17 04:09
@ramineni  the csi-cinder-plugin can support keystone double-authentication? 
i found the cloud.conf only have one field that the ca-file=/etc/ca.pem  but keystone double-authentication need cert file and clientkey? thanks for your reply

**Comment by kayrus** [comment] 2020-07-17 08:20
@jianglingxia unfortunately TLS client auth is not yet supported. It should not be hard to introduce this auth method.

**Comment by jianglingxia** [comment] 2020-07-17 09:04
ok，really thanks!

**Comment by kayrus** [comment] 2020-07-17 09:11
@jianglingxia can you test #1123?

**Comment by jianglingxia** [comment] 2020-07-17 09:19
ok,i will test it and reply the result to you,thanks

**Comment by jianglingxia** [comment] 2020-07-17 16:28
I have tested but plugin can not running the logs print   Post tokens response code 401 and print the account has lock by user xxx，is not paased the certification ？

or my step something wrong？

**Comment by kayrus** [comment] 2020-07-17 16:58
@jianglingxia can you auth with TLS against openstack using terraform or a simple curl? Is there any other working tool, which supports TLS auth?

**Comment by lingxiankong** [comment] 2020-07-24 02:25
This issue should be either closed or the description should be changed. @kayrus Your PR is not actually fixing this issue.

**Comment by jianglingxia** [comment] 2020-07-24 02:50
@lingxiankong  @kayrus  I have modify the issue description thanks

**Comment by kayrus** [comment] 2020-07-24 05:28
@lingxiankong why not? I added TLS auth support as requested.

**Comment by kayrus** [comment] 2020-07-24 05:31
@lingxiankong please upload detailed logs (with `--v=6` enabled) into https://gist.github.com. Also please post your config file.

**Comment by lingxiankong** [comment] 2020-07-27 09:25
> @lingxiankong why not? I added TLS auth support as requested.

From the issue, I only see "failed to read and parse /etc/ca.pem certificate: open /etc/ca.pem: no such file or directory", I don't think your PR is going to fix that. As the issue owner mentioned earlier, the reason is the cert file is not properly mounted.

You PR is actually to support two-way SSL authentication.

**Comment by kayrus** [comment] 2020-07-27 09:35
@lingxiankong this bug report is really confusing. If you look at the https://github.com/kubernetes/cloud-provider-openstack/issues/1119#issuecomment-659833695, you can see that authort requested TLS auth:

> i found the cloud.conf only have one field that the ca-file=/etc/ca.pem but keystone double-authentication need cert file and clientkey? thanks for your reply

@jianglingxia, please add more details on your issue.

**Comment by lingxiankong** [comment] 2020-07-27 10:30
> @lingxiankong this bug report is really confusing. If you look at the [#1119 (comment)](https://github.com/kubernetes/cloud-provider-openstack/issues/1119#issuecomment-659833695), you can see that an author requested TLS auth:
> 
> > i found the cloud.conf only have one field that the ca-file=/etc/ca.pem but keystone double-authentication need cert file and clientkey? thanks for your reply
> 
> @jianglingxia, please add more details on your issue.

This is exactly what I mean. Sometimes the discussion deviates from the original issue, that's why I asked the owner to update the description so that your PR could be mapped to this issue.

**Comment by kayrus** [comment] 2020-07-27 10:36
@lingxiankong unfrotunately the updated topic and description confuse me more than before.

**Comment by jichenjc** [comment] 2020-08-25 06:13
> 
> 
> @ramineni the csi-cinder-plugin can support keystone double-authentication?
> i found the cloud.conf only have one field that the ca-file=/etc/ca.pem but keystone double-authentication need cert file and clientkey? thanks for your reply

@jianglingxia @kayrus can you help to point me where is `double authentication`? I have https env and I can do some check but the problem is I knew cafile but not familiar with cert file and clientkey usage, and I don't think you are talking about Multi factor auth, correct?

**Comment by jianglingxia** [comment] 2020-08-25 06:20
yes,now only ca file support single authentication,need test https://github.com/kubernetes/cloud-provider-openstack/pull/1123 this pr to supprot double authentication

@kayrus sorry,my test enviorment have not exist, i can not test again, but i think your pr is right,thanks

**Comment by jianglingxia** [comment] 2020-08-25 06:20
yes,now only ca file support single authentication,need test https://github.com/kubernetes/cloud-provider-openstack/pull/1123 this pr to supprot double authentication

@kayrus sorry,my test enviorment have not exist, i can not test again, but i think your pr is right,thanks

**Comment by jianglingxia** [comment] 2020-08-25 06:20
yes,now only ca file support single authentication,need test https://github.com/kubernetes/cloud-provider-openstack/pull/1123 this pr to supprot double authentication

@kayrus sorry,my test enviorment have not exist, i can not test again, but i think your pr is right,thanks

**Comment by jichenjc** [comment] 2020-08-25 06:27
I will do more search on `double authentication` and see what I can find.. if you know , please help to share. thanks

**Comment by ramineni** [comment] 2020-09-08 09:16
@jianglingxia #1123 is merged , so issue should be fixed, if you still face the issue, feel free to reopen the issue.

**Closed by ramineni** 2020-09-08 09:16 UTC
