### ISSUE TITLE
1.28 image missing

### ISSUE THREAD

**Issue by canori01** [kubernetes/cloud-provider-openstack#2343] opened 2023-08-25 20:39 UTC
/kind bug

**What you expected to happen**:

Expected helm install  cinder-csi to work

**How to reproduce it**:
Try to helm install cinder-csi

**Anything else we need to know?**:
It looks like on pr #2337 , the image failed to build so there's no 1.28 image
See:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-openstack-push-images/1695020524926668800

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by dulek** [comment] 2023-08-28 08:12
https://github.com/kubernetes/k8s.io/pull/5758 is merged now, this should solve the problem. Please confirm if this helps and close the issue.

**Comment by clementnuss** [comment] 2023-08-28 08:18
on my side the issue is fixed. thanks for the quick fix!

**Closed** 2023-08-28 08:23 UTC
Labels: kind/bug
