### ISSUE TITLE
[occm] kubernetes_build_info metric label git_version broken ("v0.0.0-master+$Format:%h$")

### ISSUE THREAD

**Issue by MPV** [kubernetes/cloud-provider-openstack#1766] opened 2022-01-25 08:31 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Metrics from OCCM including broken `git_version` label:

`kubernetes_build_info{build_date="1970-01-01T00:00:00Z", compiler="gc", container="openstack-cloud-controller-manager", endpoint="http", git_commit="$Format:%H$", git_version="v0.0.0-master+$Format:%h$", go_version="go1.15", instance="10.224.2.228:10258", job="openstack-cloud-controller-manager", namespace="kube-system", platform="linux/amd64", pod="openstack-cloud-controller-manager-rnfxh", service="openstack-cloud-controller-manager"}`

.i.e: `git_version="v0.0.0-master+$Format:%h$"`

...causing the [`KubeVersionMismatch` alert (from kubernetes-mixin)](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/runbook.md#alert-name-kubeversionmismatch) to always fire.

**What you expected to happen**:

If we compare with other similar metrics, they look like this (i.e. `git_version="v1.19.11"`):

`kubernetes_build_info{build_date="2021-05-12T12:19:22Z", compiler="gc", endpoint="https", git_commit="c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", git_tree_state="clean", git_version="v1.19.11", go_version="go1.15.12", instance="10.224.1.228:6443", job="apiserver", major="1", minor="19", namespace="default", platform="linux/amd64", service="kubernetes"}`

**How to reproduce it**:

Look at metrics for OCCM.

**Anything else we need to know?**:

N/A

**Environment**:
- openstack-cloud-controller-manager version: v1.20.0
- OpenStack version: N/A

**Comment by jichenjc** [comment] 2022-01-26 01:54
@MPV did you try this on latest release? 
https://github.com/kubernetes/cloud-provider-openstack/pull/950 
might help you?

**Comment by zetaab** [comment] 2022-01-26 08:08
@jichenjc I am running latest from release-1.23 and it is broken.

We have fixed this now temporary by modifying kubernetes-mixin rules to exclude openstack ccm

**Comment by jichenjc** [comment] 2022-01-26 08:20
ok, I thought the problem was found and already fixed with that PR 
@ramineni might be submitter IIRC

**Comment by ramineni** [comment] 2022-01-27 04:42
@MPV @zetaab This is known issue and broken since 1.21 release. This is not provider specific , needs to be fixed from cloud-provider side.

https://github.com/kubernetes/cloud-provider-openstack/issues/1502
The same has been raised in cloudprovider repo as well, https://github.com/kubernetes/cloud-provider/issues/49

As this is duplicate issue , will be closing it

**Comment by ramineni** [comment] 2022-01-28 05:57
Duplicate of #1502
/close

**Closed** 2022-01-28 05:57 UTC
Labels: kind/bug
